feat: add group object
pyronear/pyro-api pull request #137
Opened 2021-03-20 22:30 UTC by florianriche

Create a new object called "group".
That object is linked to a user entity.
Right now, only the Unit tests and the code related to the group management has been added.

Before implementing the code linked to the authorization management, I would like opinions on this schema.

Closes #125

2021-03-21 18:22 UTC, frgfm commented
Thanks for the PR @florianriche !
Since this is a rather big deal as a feature, I think we will most likely have to split this into several PRs depending on the design :sweat_smile:
Let's discuss this in the issue #125 quickly :ok_hand:

2021-03-23 22:28 UTC, florianriche commented
> Thanks for the PR @florianriche !
> Since this is a rather big deal as a feature, I think we will most likely have to split this into several PRs depending on the design 
> Let's discuss this in the issue #125 quickly

I have updated the PR to remove the reference to group_id in user table

2021-03-24 11:51 UTC, frgfm reviewed
Hey there!
Thanks for the PR, I added a few comments. I suggest waiting for #138 to be merged before writing the actual group unittests

2021-03-24 11:51 UTC, frgfm commented on src/tests/routes/test_alerts.py
> +
Let's remove everything in the unittests that doesn't involve groups yet (so everything apart from test_groups.py)

2021-03-24 11:51 UTC, frgfm commented on src/tests/routes/test_devices.py
> +
same

2021-03-24 11:51 UTC, frgfm commented on src/app/api/schemas.py
> +class GroupBase(BaseModel):
You can rename this into GroupIn, no need for GroupBase

2021-03-24 11:51 UTC, frgfm commented on src/app/api/schemas.py
> +    pass
we can remove this

2021-03-24 11:51 UTC, frgfm commented on src/app/api/schemas.py
> +class GroupOut(GroupBase, _Id):
```
class GroupOut(GroupIn, _Id):
```

2021-03-29 10:42 UTC, frgfm requested changes
Just need to fix flake8 checks on the new unittests ;)

2021-03-29 10:51 UTC, frgfm commented
Shoot, this also needs some merging @florianriche :sweat_smile:

2021-03-29 11:06 UTC, frgfm approved these changes
Thanks for the PR! I only added a last comment about `compare_entries`: since there is no float field in the table, we can check for exact match without it. But there the rest looks good to me!

2021-03-29 11:06 UTC, frgfm commented on src/tests/routes/test_groups.py
> +            assert v == test[k]
Considering that there is no float field in the group table, perhaps we don't need this?

2021-03-29 11:06 UTC, frgfm commented on src/tests/routes/test_groups.py
> +        compare_entries(response_json, GROUP_TABLE[group_id - 1])
I think we can check for perfect match (no float field here)

2021-03-29 11:06 UTC, frgfm commented on src/tests/routes/test_groups.py
> +        compare_entries(entry, GROUP_TABLE[i])
same here

2021-03-29 11:06 UTC, frgfm commented on src/tests/routes/test_groups.py
> +        compare_entries(response.json(), GROUP_TABLE[group_id - 1])
same here

2021-03-29 11:07 UTC, merged