Add support for a s3 bucket proxy
pyronear/pyro-api pull request #287
Opened 2023-09-21 22:47 UTC by Nastaliss

2023-09-22 17:21 UTC, frgfm reviewed
Thanks! Only have two questions:
- cf. my comments but perhaps we can reduce the number of config params?
- the proxy should only be used in the test env shouldn't it? If so, changes should only appear in the dev docker compose and we'd need the local S3 service as an accessible container?

We're almost there, thanks for all your work :)

2023-09-22 17:21 UTC, frgfm commented on .github/workflows/builds.yml
> +          S3_PROXY_URL: ${{ secrets.S3_PROXY_URL }}
Can't the S3_ENDPOINT_URL be used instead? I'd be easier to minimize the number of config parmeters

2023-09-22 17:21 UTC, frgfm commented on .github/workflows/builds.yml
> +          S3_PROXY_URL: ${{ secrets.S3_PROXY_URL }}
Actually, even removing the S3_USE_PROXY, just passing the endpoint url. independently on whether it's the proxy or not

2023-09-22 17:21 UTC, frgfm commented on src/app/services/bucket/s3.py
> +        self.proxy_url = proxy_url
Can't we pass the value of proxy_url into "endpoint_url" to boto3 client?

2023-09-24 23:01 UTC, Nastaliss commented
@frgfm I used a separate url for the proxy to only use it when serving medias to the users, as the proxy is only useful in that specific case. 
Actually as the change was initiated for engie I don´t think it would only be used in dev. 
Is there a separate s3 endpoint that is used for dev ?

2023-09-26 14:27 UTC, frgfm commented on src/app/config.py
> +    S3_PROXY_URL = ""
Let's use a one line condition:
```suggestion
S3_PROXY_URL: Union[str, None] = os.environ["S3_PROXY_URL"] if S3_USE_PROXY else None
```

2023-09-26 14:28 UTC, frgfm commented on src/app/services/bucket/s3.py
> +        self.proxy_url = proxy_url
Those two should be optional if I get the purpose of this (or default to false for use_proxy, and optional for proxy_url)

2023-09-27 22:08 UTC, frgfm approved these changes
Thanks for the PR!

2023-10-13 16:55 UTC, frgfm requested changes
I think I found the problem!

2023-10-13 16:55 UTC, frgfm commented on src/app/config.py
> +S3_USE_PROXY: bool = os.environ.get("S3_USE_PROXY", "").lower() != "false"
```suggestion
S3_USE_PROXY: bool = os.environ.get("S3_USE_PROXY", "false").lower() != "false"
```

2023-10-13 17:32 UTC, frgfm approved these changes
Looks all good! Probably a permission issue from the PR since it comes from a fork (didn't know it was an issue though)

2023-10-13 17:32 UTC, merged

2023-10-18 18:31 UTC, Nastaliss commented
[issue](https://github.com/pyronear/pyro-api/issues/300)